-- KidGo schema.
--
-- IMPORTANT: this server's PostgreSQL is shared with other applications.
-- Every table here is prefixed `kidgo_` and created with IF NOT EXISTS so we
-- never touch or collide with pre-existing tables. UUIDs are generated by the
-- application (uuid crate), so no DB extensions (pgcrypto) are required.

CREATE TABLE IF NOT EXISTS kidgo_groups (
    id          TEXT PRIMARY KEY,            -- newborn | explorer | toddler | talker | creator
    emoji       TEXT NOT NULL,
    name        TEXT NOT NULL,
    age_range   TEXT NOT NULL,
    color       TEXT NOT NULL,               -- tailwind classes used by the frontend badge
    sort_order  INT  NOT NULL
);

CREATE TABLE IF NOT EXISTS kidgo_spots (
    id     TEXT PRIMARY KEY,
    name   TEXT NOT NULL,
    area   TEXT NOT NULL,
    type   TEXT NOT NULL,
    ages   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS kidgo_users (
    id          UUID PRIMARY KEY,
    nickname    TEXT NOT NULL,
    phone       TEXT UNIQUE NOT NULL,        -- WhatsApp number, digits only (E.164 without +)
    city        TEXT NOT NULL DEFAULT 'Maastricht',
    child_stage TEXT REFERENCES kidgo_groups(id),
    interests   TEXT[] NOT NULL DEFAULT '{}',-- group ids the parent is interested in
    push_optout BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS kidgo_activities (
    id          UUID PRIMARY KEY,
    title       TEXT NOT NULL,
    group_id    TEXT NOT NULL REFERENCES kidgo_groups(id),
    spot_id     TEXT NOT NULL REFERENCES kidgo_spots(id),
    area        TEXT NOT NULL,
    tags        TEXT[] NOT NULL DEFAULT '{}',
    starts_at   TIMESTAMPTZ NOT NULL,
    recurring   BOOLEAN NOT NULL DEFAULT FALSE,
    host_id     UUID NOT NULL REFERENCES kidgo_users(id),
    capacity    INT NOT NULL DEFAULT 6,
    notes       TEXT,
    status      TEXT NOT NULL DEFAULT 'open',-- open | cancelled
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS kidgo_participants (
    activity_id UUID NOT NULL REFERENCES kidgo_activities(id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES kidgo_users(id) ON DELETE CASCADE,
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (activity_id, user_id)
);

CREATE TABLE IF NOT EXISTS kidgo_messages (
    id          UUID PRIMARY KEY,
    activity_id UUID NOT NULL REFERENCES kidgo_activities(id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES kidgo_users(id),
    body        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS kidgo_match_suggestions (
    id           UUID PRIMARY KEY,
    activity_id  UUID NOT NULL REFERENCES kidgo_activities(id) ON DELETE CASCADE,
    suggested_id UUID NOT NULL REFERENCES kidgo_activities(id) ON DELETE CASCADE,
    score        DOUBLE PRECISION NOT NULL,
    pushed       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (activity_id, suggested_id)
);

CREATE INDEX IF NOT EXISTS kidgo_activities_starts_at_idx ON kidgo_activities (starts_at);
CREATE INDEX IF NOT EXISTS kidgo_activities_group_idx     ON kidgo_activities (group_id);
CREATE INDEX IF NOT EXISTS kidgo_messages_activity_idx    ON kidgo_messages (activity_id);
